version: "2"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - JWT_KEY=CvRwumWVwekKBPQm
      - APP_PORT=8000
      - APP_URL='http://localhost:8000'
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432

    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - api
  migration:
    build: ./api
    command: ["sh", "-c", "./scripts/wait-for.sh db:5432 -- npm run db:preload"]
    environment:
      - NODE_ENV=development
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432
    links:
      - db
    depends_on:
      - db
